### PR TITLE
Bump graphql to 0.9.0

### PR DESCRIPTION
**Pull request by jonbretman**
0.9.0 was released today - https://github.com/graphql/graphql-js/releases/tag/v0.9.0

### CODE REVIEW

**Comment by jnwng** [comment]
thank you @jonbretman!

**Comment by jonbretman** [comment]
No worries. I noticed you bumped the version to 0.6.0 but it doesn't look like it's been published to npm. Can someone do a release?

**Comment by jnwng** [comment]
@jonbretman yep - just reached out to @helfer to cut a new release. we'll adjust the workflow so that whoever has permissions to cut releases does the github version bump too so there isn't this lag time between github and npm

**Comment by jnwng** [comment]
this should be live now!

**Comment by jonbretman** [comment]
Excellent thanks!

**Pull request merged**
