### PR TITLE
Added 'literal' option to env

### PR DESCRIPTION
**Pull request by jtmthf**
From #35 

Just use `env: 'literal'` to use literal grapnel files with either `.graphql` or `.gql` as an extension. No need to modify `tagName`.

Also added yarn lock.

### CODE REVIEW

**Comment by stubailo** [comment]
> Also added yarn lock.

I don't think we want a yarn lock file in a library - consistent builds are actually a disadvantage when testing an npm package since people who install it are always going to get the newest versions of dependencies. Can you remove it please?

Also, can we add documentation about this new env to the README?

**Comment by jtmthf** [comment]
Yeah I can go ahead and do that. For docs, in addition to configuring the .eslintrc.js file, what about editor integration? I haven't tested in Atom yet, but it's eslint plugin should work fine after making a change to the settings. For VSCode, I had to use a beta version of the eslint extension, make a configuration change, and install a graphql extension to work.

**Comment by stubailo** [comment]
Oh I was just thinking about documenting the new env you added. We could definitely use better documentation about how to set up editor integration for `.graphql` files, but that should be a separate PR I think.

**Comment by stubailo** [comment]
@jtmthf ah, one last thing sorry - can you add to the changelog so I can publish a new version? This looks great now.

**Comment by jtmthf** [comment]
@stubailo Should I mark it as v0.4.1?

**Comment by stubailo** [comment]
Just putting it under `vNEXT` is fine - I'll change that to the next version after merging. Just asking you to write the change description.

**Comment by stubailo** [comment]
Published in 0.4.2!

**Pull request merged**
