### PR TITLE
Fix required fs import for `schemaJsonFilepath` option

### PR DESCRIPTION
**Pull request by nodkz**
Sorry for the inconvenience. I don't know how it happens, but I somehow missed `import fs from 'fs';` in my previous PR https://github.com/apollostack/eslint-plugin-graphql/pull/20 (which on npm right now). 😇

screen shot 2016-11-04 at 10 42 40
screen shot 2016-11-04 at 10 42 29

Please merge and bump new version. Thanks.

### CODE REVIEW

**Comment by nodkz** [comment]
@stubailo please republish package with this fix
Thnx

**Comment by stubailo** [comment]
Oh gosh, sorry about being so late - was chilling out over the weekend.

**Comment by stubailo** [comment]
Would you mind contributing some unit tests for this feature? That would avoid errors like this in the future.

**Comment by stubailo** [comment]
Published 0.2.7.

**Comment by nodkz** [comment]
eslint-plugin-graphql@0.2.7 works like a charm
Thanks. Test added in other PR.

**Pull request merged**
